allowedBuiltDependencies:
  - contentlayer2
  - esbuild
ignoredBuiltDependencies:
  - "@stellar/stellar-sdk"
  - blake-hash
  - bufferutil
  - protobufjs
  - sharp
  - tiny-secp256k1
  - usb
  - utf-8-validate
